### ISSUE TITLE
Decide if Non-Bike Options Should Be Supported

### ISSUE THREAD

**Issue by conor-f** [conor-f/via-web#23]
This is ultimately a visualization of road quality, safety, usage, etc for bikes, not cars. Should any option not bike be shown to users?

**Comment by RobertLucey** [comment]
Think this has already been decided, at least the Web and api default to bikes, the other selectors are still on the app but that's the app...

**Comment by conor-f** [comment]
Yup gonna clear up the issues. The "Project" automations don't seem to close them which is dumb
