### ISSUE TITLE
Segment colour by other numerical properties

### ISSUE THREAD

**Issue by RobertLucey** [conor-f/via-web#38]
I think it would be good to have an input to as well as show quality of segments by colour, show speed and collision counts by colour

Looking at the numbers it's just not apparent how fast / dangerous segments are

**Comment by conor-f** [comment]
You got it

**Comment by conor-f** [comment]
Check #40 for the fix :)

Cleaned up the colour selection to make it easier to understand also. It now does a simple % scale between a min and max value. e.g. if you set `minVal=55; maxVal=65;`, `60` will evaluate to `50%` the way through the red -> green spectrum.
